server:
  servlet:
    context-path: "/api/v1"
  port: 8085
spring:
  application:
    name: BOOKING-SERVICE-DEV

  datasource:
    # url: jdbc:mysql://localhost:3306/bookingservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    # username: root
    # password: Pass@123
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/bookingservice?sslMode=VERIFY_IDENTITY
    # username: 39eTZA21moCVeit.root
    # password: JNkHil67UBnTv1ea
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
    username: postgres.ocsbcjafyeugenkiknvz
    password: Tut4mvoKMiGTrqfD
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

resilience4j:
  retry:
    retryAspectOrder: 2
    instances:
      hotel-service-retry:
        maxAttempts: 3
        waitDuration: 5s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
      user-service-retry:
        maxAttempts: 3
        waitDuration: 5s  
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2        

  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      user-service-cb:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 1m
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      hotel-service-cb:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 1m
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true   

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,retry,retryevents

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

  info:
    env:
      enabled: true

info:
  app:
    name: BOOKING-SERVICE
    description: Booking Service API
    version: 1.0



