server:
  port: 8087
  servlet:
    context-path: "/api/v1"

spring:
  application:
    name: NOTIFICATION-SERVICE-DEV

  mail:
    host: smtp.gmail.com
    port: 587
    username: abhishek.kanade.dev@gmail.com
    password: bnwa bkcn enys wblt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
    username: postgres.ocsbcjafyeugenkiknvz
    password: Tut4mvoKMiGTrqfD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true



resilience4j:
  retry:
    retryAspectOrder: 2
    instances:
      send-email-retry:
        maxAttempts: 3
        waitDuration: 5s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - software.amazon.awssdk.core.exception.SdkClientException
          - software.amazon.awssdk.services.sesv2.model.TooManyRequestsException

  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      send-email-cb:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 1m
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,retry,retryevents

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

  info:
    env:
      enabled: true

info:
  app:
    name: NOTIFICATION-SERVICE
    description: Notification Service API
    version: 1.0
