server:
  servlet:
    context-path: "/api/v1"
  port: 8083

spring:
  application:
    name: RATING-SERVICE-PROD

  datasource:
    # url: jdbc:mysql://localhost:3306/ratingservice?useSSL=false&serverTimezone=UTC
    # username: root
    # password: Pass@123
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres
    username: postgres.ocsbcjafyeugenkiknvz
    password: Tut4mvoKMiGTrqfD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        # dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

resilience4j:
  retry:
    retryAspectOrder: 2
    instances:
      userServiceRetry:
        maxAttempts: 3
        waitDuration: 5s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2 
      hotelServiceRetry:
        maxAttempts: 3
        waitDuration: 5s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2  

  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      userServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 1m
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      hotelServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 1m
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true   

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,retries,retryevents

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

  info:
    env:
      enabled: true

info:
  app:
    name: RATING-SERVICE
    description: Rating Service API
    version: 1.0
